In [1]:
%load_ext autoreload
%autoreload 2
from napari.qt.threading import thread_worker
import control
import napari
import gui
import time
import numpy as np

In [46]:
c.snap()

array([[24613, 25193, 26493, ..., 44956, 45490, 44335],
       [24971, 24613, 24472, ..., 41890, 42768, 44747],
       [25884, 24415, 24511, ..., 41577, 42125, 45096],
       ...,
       [59574, 57156, 57166, ..., 47110, 47142, 50554],
       [60618, 57621, 56782, ..., 47145, 47929, 48542],
       [59359, 59838, 59903, ..., 50149, 48408, 47929]], dtype=uint16)

In [2]:
config = {
    "valves": {
        "ip": "192.168.1.2",
        "device": "wago_valves"
    },
    "mux": {
        "device": "mux",
        "mapping": {
            "0_0": 47,
            "0_1": 46,
            "1_0": 45,
            "1_1": 44,
            "2_0": 43,
            "2_1": 42,
            "3_0": 41,
            "3_1": 40,
            "waste": 37,
            "io": 36,
        }
    },
    "mc": {
        "device": "minichip",
        "mapping": {
            "0_0": 31,
            "0_1": 30,
            "1_0": 28,
            "1_1": 27,
            "2_0": 26,
            "2_1": 25,
            "buttons": 24,
            "sandwiches": 29,
        }
    },
    "camera": {
        "device": "zyla_camera"
    },
    "objective": {
        "device": "ti2_objective",
        "states": ["4x", "?", "4x", "??", "???", "????"],
        "zooms": [0, 10, 4, 0, 0, 0]
    },
    "light": {
        "device": "sola_light",
        "port": "COM3"
    },
    "up_filter": {
        "device": "ti2_filter1",
        "states": ["mcherry", "egfp", "open1", "cy5", "brightfield", "open2"]
    },
    "down_filter": {
        "device": "ti2_filter2"
    },
    "stage": {
        "device": "asi_stage",
        "port": "COM4"
    },
    "focus": {
        "device": "ti2_focus"
    },
    "lightpath": {
        "device": "ti2_lightpath"
    },
}
c = control.load(config, path="C:/Users/karlk/Micro-Manager-2.0")
c._core.setTimeoutMs(100000)
c.exposure = 100
c.objective = "4x"

RuntimeError: Cannot get current position label

In [101]:
c.valves[46] = 1

In [105]:
c.mc.io = "open"

In [ ]:
def open_waste():
    c.valves[43] = 1
    c.valves[44] = 0
"1_0": 45,
"1_1": 44,
"2_0": 43,
"2_1": 42,

In [103]:
c.valves[44] = 0

In [102]:
c.mux = "closed"

In [ ]:
import time
pbs = 0
bbsa = 1
na = 2
ab = 3
c.mux = "closed"
c.mc.snw = 0
c.mc.btn = 0


In [ ]:
print('>> 1/18. Starting Device Patterning for devices {}. \
    Starting with all valves closed. NOTE: flow of non-biotinylated BSA \
    should have already been done')
print('2/18. Opening sandwiches, outlet, bBSA inlet, and waste. \
    Flushing bBSA through inlet tree to waste for 30s')

vc.openValves(devices, sandwichValves + outlet + bbsaValve + wasteValve)
time.sleep(30)

print('3/18. Done Flushing bBSA to waste. Flushing bBSA through \
    devices with buttons closed for 5min')
vc.closeValves(devices, wasteValve)
vc.openValves(devices, inletValve)
time.sleep(300)

print('4/18. Opened buttons with bBSA flowing through devices to waste for 35min')
vc.openValves(devices, buttonValves)
time.sleep(2100)

print('5/18. Done Flowing bBSA through devices and closed inlet. \
    Flushing PBS through inlet tree to waste for 30s')
vc.closeValves(devices, bbsaValve + inletValve)
vc.openValves(devices, bufferValve + wasteValve)
time.sleep(30)

print('6/18. Done flowing PBS to waste. Flushing PBS through device \
    with  buttons open for 10min')
vc.closeValves(devices,  wasteValve)
vc.openValves(devices, inletValve)
time.sleep(600)

print('7/18. Done flushing PBS through devices. \
    Flowing neutravidin through inlet tree to waste for 30s')
vc.closeValves(devices, bufferValve + inletValve)
vc.openValves(devices, naValve + wasteValve)
time.sleep(30)

print('8/18. Done flushing Neutravidin to waste. \
    Flowing Neutravidin through devices with buttons open for 30min')
vc.closeValves(devices, wasteValve)
vc.openValves(devices, inletValve)
time.sleep(1800)

print('9/18. Done flowing Neutravidin through devices. \
    Flowing PBS through devices with buttons open for 10min')
vc.closeValves(devices, naValve)
vc.openValves(devices, bufferValve)
time.sleep(600)

print('10/18. Done flowing PBS through devices and closed buttons. \
    Flowing bBSA through the device for another 35min (quench walls only)')
vc.closeValves(devices, bufferValve + buttonValves)
vc.openValves(devices, bbsaValve)   
time.sleep(2100)

print('11/18. Done flowing bBSA through devices. \
    Flowing PBS through the device for 10min. **NEXT STEP IS ANTIBODY FLOWING**')
vc.closeValves(devices, bbsaValve)
vc.openValves(devices, bufferValve)
time.sleep(600)

print('12/18. Done flowing PBS through devices and closed inlet. \
    Flowing Antibody through inlet tree to waste for 30s')
vc.closeValves(devices, bufferValve + inletValve)
vc.openValves(devices, antibodyValve + wasteValve)
time.sleep(30)
        
print('13/18. Done flowing Antibody through inlet tree. Flowing \
    Antibody through device for 2min')
vc.closeValves(devices, wasteValve)
vc.openValves(devices, inletValve)
time.sleep(120)

print('14/18. While flowing Antibody through devices, opened buttons. \
    Flowing for 13.3min')
vc.openValves(devices, buttonValves)
time.sleep(800)

print('15/18. Closed buttons while flowing Antibody through device for 30s')
vc.closeValves(devices, buttonValves)
time.sleep(30)

print('16/18. Done flowing Antibody through device. Flowing PBS through \
    inlet tree to waste for 30s')
vc.closeValves(devices, antibodyValve + inletValve)
vc.openValves(devices, bufferValve + wasteValve)
time.sleep(30)      

print('17/18. Done flowing PBS to waste. Flowing PBS through device for 10min')
vc.closeValves(devices, wasteValve)
vc.openValves(devices, inletValve)
time.sleep(600)

print('18/18. Closed the outlets')
vc.closeValves(devices, outlet)

print('>> Done with device patterning')


In [71]:
gui.live(c)

(Viewer(camera=Camera(center=(0.0, 1023.5, 1023.5), zoom=0.28759765625, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2048.0, 1.0), (0.0, 2048.0, 1.0)), current_step=(1023, 1023), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'live' at 0x1f4a60882b0>], help='use <2> for transform', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001F41026E9E0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}),
 <napari._qt.qthreading.GeneratorWorker at 0x1f411e95ea0>)

In [68]:
c.mc.snw = 0

In [10]:
c._core.setState("objective", 0)

RuntimeError: Cannot get position label at index 0

In [7]:
gui.live(c)

(Viewer(camera=Camera(center=(0.0, 1023.5, 1023.5), zoom=0.28759765625, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2048.0, 1.0), (0.0, 2048.0, 1.0)), current_step=(1023, 1023), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'live' at 0x1f420a64ee0>], help='use <2> for transform', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001F41026E9E0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}),
 <napari._qt.qthreading.GeneratorWorker at 0x1f420c7d480>)

In [11]:
c._core.loadDevice("dia", "NikonTi2","DiaLamp")

In [ ]:
pbs = 0


In [45]:
c.mux = "waste"

In [12]:
c._core.initializeDevice("dia")

In [13]:
c._core.setProperty("dia", "State", "1")

In [198]:
c.valves[26] = 1

In [18]:
c.exposure = 1

In [146]:
for i in range(30, 40):
    c.valves[i] = 1

In [173]:
c._core.setProperty("dia", "State", "0")

In [181]:
c.valves[40] = 1

In [184]:
for i in range(30):
    time.sleep(1)
    for j in range(24, 32):
        c.valves[j] = 0
    time.sleep(1)
    for j in range(24, 32):
        c.valves[j] = 1

In [7]:
gui.live(c)

(Viewer(camera=Camera(center=(0.0, 1023.5, 1023.5), zoom=0.28759765625, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2048.0, 1.0), (0.0, 2048.0, 1.0)), current_step=(1023, 1023), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'live' at 0x205a20769b0>], help='use <2> for transform', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000020591D56B90>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}),
 <napari._qt.qthreading.GeneratorWorker at 0x205a20e6320>)

  File "C:\Users\karlk\miniforge3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\karlk\miniforge3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\karlk\miniforge3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\karlk\miniforge3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\karlk\miniforge3\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\karlk\miniforge3\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\karlk\miniforge3\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\karlk\miniforge3\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\karlk\miniforge3\lib\asy

In [8]:
c.exposure = 1

In [182]:
c._core.setProperty("dia", "State", "0")

In [116]:
c._core.getAllowedPropertyValues("dia", "State")

('0', '1')

In [93]:
c._core.getProperty("light", "Description")

'Lumencor Spectra Light Engine'

In [76]:
c._core.getDevicePropertyNames("light")

('Description',
 'Name',
 'Port',
 'SetLE_Type',
 'State',
 'White_Enable',
 'White_Level')

In [110]:
c.valves[44] = 1

In [12]:
c.valves[28] = "on"
time.sleep(1)
c.valves[28] = "off"

In [89]:
for i in range(24, 32):
    c.valves[i] = "off"

In [84]:
c.mc.snw = "open"

In [92]:
c.mc.btn = "open"

In [91]:
c.mc.snw = "open"

In [15]:
c._core.setProperty("down_filter", "State", 4)

In [65]:
c.light = 0

In [20]:
c.wait()
c.objective = 0

In [5]:
c._core.setProperty("objective", "State", "4")

In [28]:
c._core.getProperty("objective", "State")

'0'

In [24]:
c._core.getAllowedPropertyValues("objective", "State")

('0', '1', '2', '3', '4', '5')

In [6]:
c._core.getDevicePropertyNames("obj")

('Label', 'State')

In [171]:
c.valves[37] = 0

In [21]:
c._core.setProperty("objective", "Magnification", "1.5x")

In [9]:
c._core.getInstalledDevices("ti2_scope")

('ZDrive',
 'Nosepiece',
 'FilterTurret1',
 'Turret1Shutter',
 'FilterTurret2',
 'Turret2Shutter',
 'LightPath',
 'IntermediateMagnification',
 'DiaLamp')

In [7]:
c._core.getAllowedPropertyValues("obj", "State")


('0', '1', '2', '3', '4', '5')

In [44]:
res = gui.live(c)

In [45]:
c.z = 5000

In [10]:
c.mc.btn = "open"

In [64]:
c.uv_shutter = "closed"

sys:1: RuntimeWarning: RuntimeError in aborted thread: Error in device "camera":  Snap Image Failure (25)


In [72]:
c.mux = "closed"

[1 1 1 1]
[0 0 0 0]


In [20]:
c.right_filter = "620"

In [32]:
for i in range(30):

array([[123, 108, 118, ..., 127, 139, 133],
       [129, 131, 130, ..., 127, 139, 122],
       [135, 120, 140, ..., 124, 131, 136],
       ...,
       [120, 145, 104, ..., 141, 131, 125],
       [124, 141, 112, ..., 126, 125, 147],
       [132, 132, 128, ..., 133, 110, 127]], dtype=uint16)

In [109]:
# Want to have an easy way to specify exposures across channels
c.exposure = 100

Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)


In [3]:
viewer, worker = gui.live(c)

In [4]:
c.z = 5000

In [6]:
c.devices["objective"].state = "a"

TypeError: list indices must be integers or slices, not str

In [8]:
c.exposure = 100

In [121]:
c.right_filter = "open"
c.top_filter = "open1"
c.laser = "closed"
c.light = 0
c.exposure = 10

## Tiling

In [48]:
c.up_filter = "cy5"

In [66]:
c.light = 100

In [120]:
c.right_filter = "620"
c.top_filter = "open1"
c.laser = "open"
c.light = 0
c.exposure = 100

Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)


In [112]:
top_left = c.xy

In [113]:
bottom_right = c.xy

In [11]:
c.z = 5000

RuntimeError: Error in device "focus": (Error message unavailable) (-9)

In [60]:
c.right_filter = "open"

In [87]:
top_channels = ["cy5"]
right_channels = ["620"]

In [96]:
overlap_pixels = 100
um_per_pixel = 1.6137
img = c.snap()
img_height_pixels = img.shape[0]
img_width_pixels = img.shape[1]
img_height_um = um_per_pixel * img.shape[0]
img_width_um = um_per_pixel * img.shape[1]
overlap_um = overlap_pixels * um_per_pixel
delta_x = img_width_um - overlap_um
delta_y = img_height_um - overlap_um
xs = np.arange(top_left[0], bottom_right[0], delta_x)
ys = np.arange(top_left[1], bottom_right[1], delta_y)

canvas = np.zeros((len(top_channels) + len(right_channels),
                (img_height_pixels - overlap_pixels) * len(ys) + overlap_pixels,
                (img_width_pixels - overlap_pixels) * len(xs) + overlap_pixels), dtype=np.uint16)
viewer, layers = napari.imshow(canvas, channel_axis=0, contrast_limits=[0, 65535], name=top_channels + right_channels)
def update_canvas(d):
    d, i, j, c = d[0], d[1], d[2], d[3]
    row = i * (img_height_pixels - overlap_pixels)
    col = j * (img_width_pixels - overlap_pixels)
    viewer.layers[c].data[row:row + img_height_pixels, col:col + img_width_pixels] = d
    viewer.layers[c].refresh()

@thread_worker(connect={"yielded": update_canvas})
def tile_images():
    c.uv_filter = "uv"
    for i, y in enumerate(ys):
        for j, x in enumerate(xs):
            c.xy = (x, y)
            c._core.waitForDevice("stage")
            c.right_filter = "open"
            c.laser = "closed"
            c.light = 100
            c.exposure = 1000
            time.sleep(3)
            for channel in top_channels:
                c.up_filter = channel
                time.sleep(1)
                yield (c.snap(), i, j, channel)
                c._core.waitForDevice("camera")
                time.sleep(1)

            c.up_filter = "open1"
            c.laser = "open"
            c.exposure = 1000
            c.light = 0
            for channel in right_channels:
                c.right_filter = channel
                time.sleep(1)
                yield (c.snap(), i, j, channel)
                c._core.waitForDevice("camera")
                time.sleep(1)
            time.sleep(1)

In [97]:
worker2 = tile_images()

In [19]:
worker2.quit()

In [18]:
c.devices[0].wait()

Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap

In [104]:
c.laser = "closed"

In [4]:
c.z = 5000

In [11]:
c.light = 0

In [3]:
c.exposure

3.0048

In [20]:
c.valves[47] = "open"

In [11]:
c.close()

In [33]:
for i in range(48):
    c.valves[i] = "closed"

for i in range(48):
    time.sleep(0.1)
    c.valves[i] = "open"

In [25]:
c.z = 5000

In [32]:
c.valves[9] = "closed"

In [102]:
layers[0].contrast_limits = [0, 65000]

In [103]:
layers[1].contrast_limits = [0, 65000]

In [115]:
c._core.isBufferOverflowed()

False

Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)


In [116]:
c._core.getBufferTotalCapacity()

0

Error in device "camera":  Snap Image Failure (25)


In [118]:
c._core.getBufferFreeCapacity()

0

Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)
Error in device "camera":  Snap Image Failure (25)


In [74]:
c.mux = "open"

[1 1 0 0]
[0 0 1 1]


In [73]:
c.mux = 3

[0 0 0 0]
[1 1 1 1]


In [63]:
c.mux

[0 1 1 1]
[1 0 0 0]
[0 1 1 1]
[1 0 0 0]


8